########################################################################
#
# basic Makefile for AST class library
#
########################################################################
# Tool Defines
########################################################################
CXXFLAGS = -O1 -g3 -Wall -fmessage-length=0
CXX = g++
########################################################################
# Sources
########################################################################
SRC = 	[% FOREACH class = classdata -%] src/[% class %]_astNode.cpp [% END %] leaf_astNode.cpp

OBJ = $(SRC:.cpp=.o)

TARGET = libast.a

INCS = -I. -I../include/ 
INCS += -I./src/
INCS += -I./../parser/
INCS += -I./../logging/
INCS += -I./../tac/

# library paths
LIBS = -lstdc++

.SUFFIXES: .cpp

default: $(TARGET)

.cpp.o:
	$(CXX) $(INCS) $(CCFLAGS) -c $< -o $@

$(TARGET): $(OBJ)
	ar rcs $(TARGET) $(OBJ)

depend: dep

dep:
	makedepend -- $(CXXFLAGS) -- $(INCS) $(SRC)

clean:
	rm -f $(OBJ) $(TARGET)

